apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  selector:
    app: items
  ports:
    - protocol: TCP
      port: 3001          # Port on the service
      targetPort: 3001    # Port inside the container
      nodePort: 30001
  type: NodePort