apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 3002          # Port on the service
      targetPort: 3002    # Port inside the container
      nodePort: 30002
  type: NodePort